  train_csv_path: /content/train.csv
  sample_sub_csv_path: /content/sample_submission.csv
  mode: segmentation

  io_params:
    image_folder: /content/test_images
    batch_size: 18
    num_workers: 0
    aug_key: aug2

  model_params:
    encoders:
      - se_resnext50_32x4d
      - se_resnext50_32x4d
    decoders:
      - FPN
      - Unet
    Unet:
      attention_type: ~ # scse
      decoder_use_batchnorm: True # inplace for InplaceABN
    FPN:
      dropout: 0.2

  checkpoint_paths:
    - /content/fpn_resnext50_32x4d_seed200_23epochs_aug2_fullimg2_best.pth
    - /content/uresnext50_32x4d_seed200_23epochs_aug2_fullimg2_best.pth

  infer_params:
    tta_flips: #~
      - lr_flip
      # - ud_flip
      # - lrud_flip
    class_params:
      0:
        - 0.5
        - 10000
      1:
        - 0.5
        - 10000
      2:
        - 0.5
        - 10000
      3:
        - 0.5
        - 10000
